spring.profiles.active=mysql

# app
spring.application.name=id-generator.ituknown.cn
server.port=8080

# mybatis
mybatis-plus.global-config.banner=false
# mybatis-plus.mapper-locations=classpath*:mapper/**/*.xml

spring.jackson.time-zone=Asia/Shanghai

id.segment.init_id=10000
id.segment.step=1000