# postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/id_generator_db
spring.datasource.username=admin
spring.datasource.password=admin123

# mybatis
mybatis-plus.global-config.db-config.schema=public